#!/usr/bin/env bash
#
# Deploys the commitbit microservice
#

cat serverless.yml.template | \
  sed s/{GITHUB_WEBHOOK_SECRET}/${GITHUB_WEBHOOK_SECRET}/ | \
  sed s/{GITHUB_TEAM_ID}/${GITHUB_TEAM_ID}/ | \
  sed s/{GITHUB_AUTH_TOKEN}/${GITHUB_AUTH_TOKEN}/ > \
  serverless.yml

serverless deploy -v
